brain_two/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("todos/", include("todos.urls")),
]

todos/urls.py
from django.urls import path

from todos.views import (
    TodoCreateView,
    TodoListView,
    TodoDetailView,
    TodoUpdateView,
    TodoDeleteView,
    TodoItemCreateView,
)

urlpatterns = [
    path("", TodoListView.as_view(), name="todos_list_list"),
    path("<int:pk>/", TodoDetailView.as_view(), name="todo_list_detail"),
    path("create/", TodoCreateView.as_view(), name="todo_list_create"),
    path("<int:pk>/edit", TodoUpdateView.as_view(), name="todo_list_update"),
    path("<int:pk>/delete", TodoDeleteView.as_view(), name="todo_list_delete"),
    path("items/create", TodoItemCreateView.as_view(), name="todo_item_create"),
]

todos/models.py
from django.db import models


class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(null=True, blank=True)
    is_completed = models.BooleanField()
    list = models.ForeignKey(
        "TodoList", related_name="items", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.task

todos/views.py
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from todos.models import TodoList, TodoItem


class TodoListView(ListView):
    model = TodoList
    template_name = "todos/list.html"


class TodoDetailView(DetailView):
    model = TodoList
    template_name = "todos/detail.html"


class TodoCreateView(CreateView):
    model = TodoList
    template_name = "todos/create.html"
    fields = ["name"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.id])


class TodoUpdateView(UpdateView):
    model = TodoList
    template_name = "todos/edit.html"
    fields = ["name"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.id])


class TodoDeleteView(DeleteView):
    model = TodoList
    template_name = "todos/delete.html"
    success_url = reverse_lazy("todo_list_list")


class TodoItemCreateView(CreateView):
    model = TodoItem
    template_name = "todos/item_create.html"
    fields = ["task", "due_date", "is_completed", "list"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.id])

todos/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Recipe - Scrumptious</title>
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
</head>

<body>
    {% block content %}
    {% endblock content %}
</body>

</html>

todos/templates/todos/create.html
{% extends 'base.html' %}
{% block content %}
<main>
    <div>
        <h1>Create a new list</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Create</button>
        </form>
    </div>
</main>
{% endblock content %}

todos/templates/todos/delete.html
{% extends 'base.html' %}
{% block content %}
<main>
    <div>
        <h1>Are you sure?</h1>
        <form method="POST">
            {% csrf_token %}
            <button>Delete</button>
        </form>
    </div>
</main>
{% endblock content %}

todos/templates/todos/detail.html
{% extends 'base.html' %}
{% block content %}
<main>
    <div>
        <h1>{{ todolist.name }}</h1>
        <p>
            <a href="{% url 'todo_list_update' todolist.pk %}">Edit</a>
        </p>
        <p>
            <a href="{% url 'todo_list_delete' todolist.pk %}">Delete</a>
        </p>
        <h2>Tasks</h2>
        <table>
            <thead>
                <th>Task</th>
                <th>Due Date</th>
            </thead>
            <tbody>
                {% for item in todolist.items.all %}
                <tr>
                    <td>{{ item.task }}</td>
                    <td>{{ item.due_date }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</main>
{% endblock content %}

todos/templates/todos/edit.html
{% extends 'base.html' %}
{% block content %}
<main>
    <div>
        <h1>Update list</h1>
        <form method="POST">
            {% csrf_token %}
            <input type="text" name="name">
            <button>Update</button>
        </form>
    </div>
</main>
{% endblock content %}

todos/templates/todos/item_create.html
{% extends 'base.html' %}
{% block content %}
<main>
    <div>
        <h1>Create a new item</h1>
        <form method="POST">
            {% csrf_token %}
            {{form.as_p }}
            <button>Create</button>
        </form>
    </div>
</main>
{% endblock content %}

todos/templates/todos/list.html
{% extends 'base.html' %}
{% block content %}
<main>
    <div>
        <h1>My Lists</h1>
        <p>
            <a href="{% url 'todo_list_create' %}">Create a new list</a>
        </p>
        <p>
            <a href="{% url 'todo_item_create' %}">Create a new item</a>
        </p>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Number of items</th>
                </tr>
            </thead>
            <tbody>
                {% for todo_list in todolist_list %}
                <tr>
                    <td>
                        <a href="{% url 'todo_list_detail' todo_list.pk %}">{{ todo_list.name }}</a>
                    </td>
                    <td>{{ todolist.items.all|length }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</main>
{% endblock content %}